namespace FacialCaptureSync
{
    public static class FacialCaptureUtility
    {
        public static int GetBoneIndex(string boneName)
        {
            var index = boneName switch
            {
                nameof(BoneName.head) => (int)BoneName.head,
                nameof(BoneName.rightEye) => (int)BoneName.rightEye,
                nameof(BoneName.leftEye) => (int)BoneName.leftEye,
                nameof(BoneName.neck) => (int)BoneName.neck,
                nameof(BoneName.spine) => (int)BoneName.spine,
                _ => -1,
            };
            return index;
        }

        public static int GetBlendShapeIndex(string blendShapeName)
        {
            var index = blendShapeName switch
            {
                // Pascal case
                nameof(BlendShapeName.BrowDownLeft)        => (int)BlendShapeName.BrowDownLeft,
                nameof(BlendShapeName.BrowDownRight)       => (int)BlendShapeName.BrowDownRight,
                nameof(BlendShapeName.BrowInnerUp)         => (int)BlendShapeName.BrowInnerUp,
                nameof(BlendShapeName.BrowOuterUpLeft)     => (int)BlendShapeName.BrowOuterUpLeft,
                nameof(BlendShapeName.BrowOuterUpRight)    => (int)BlendShapeName.BrowOuterUpRight,
                nameof(BlendShapeName.CheekPuff)           => (int)BlendShapeName.CheekPuff,
                nameof(BlendShapeName.CheekSquintLeft)     => (int)BlendShapeName.CheekSquintLeft,
                nameof(BlendShapeName.CheekSquintRight)    => (int)BlendShapeName.CheekSquintRight,
                nameof(BlendShapeName.EyeBlinkLeft)        => (int)BlendShapeName.EyeBlinkLeft,
                nameof(BlendShapeName.EyeBlinkRight)       => (int)BlendShapeName.EyeBlinkRight,
                nameof(BlendShapeName.EyeLookDownLeft)     => (int)BlendShapeName.EyeLookDownLeft,
                nameof(BlendShapeName.EyeLookDownRight)    => (int)BlendShapeName.EyeLookDownRight,
                nameof(BlendShapeName.EyeLookInLeft)       => (int)BlendShapeName.EyeLookInLeft,
                nameof(BlendShapeName.EyeLookInRight)      => (int)BlendShapeName.EyeLookInRight,
                nameof(BlendShapeName.EyeLookOutLeft)      => (int)BlendShapeName.EyeLookOutLeft,
                nameof(BlendShapeName.EyeLookOutRight)     => (int)BlendShapeName.EyeLookOutRight,
                nameof(BlendShapeName.EyeLookUpLeft)       => (int)BlendShapeName.EyeLookUpLeft,
                nameof(BlendShapeName.EyeLookUpRight)      => (int)BlendShapeName.EyeLookUpRight,
                nameof(BlendShapeName.EyeSquintLeft)       => (int)BlendShapeName.EyeSquintLeft,
                nameof(BlendShapeName.EyeSquintRight)      => (int)BlendShapeName.EyeSquintRight,
                nameof(BlendShapeName.EyeWideLeft)         => (int)BlendShapeName.EyeWideLeft,
                nameof(BlendShapeName.EyeWideRight)        => (int)BlendShapeName.EyeWideRight,
                nameof(BlendShapeName.JawForward)          => (int)BlendShapeName.JawForward,
                nameof(BlendShapeName.JawLeft)             => (int)BlendShapeName.JawLeft,
                nameof(BlendShapeName.JawOpen)             => (int)BlendShapeName.JawOpen,
                nameof(BlendShapeName.JawRight)            => (int)BlendShapeName.JawRight,
                nameof(BlendShapeName.MouthClose)          => (int)BlendShapeName.MouthClose,
                nameof(BlendShapeName.MouthDimpleLeft)     => (int)BlendShapeName.MouthDimpleLeft,
                nameof(BlendShapeName.MouthDimpleRight)    => (int)BlendShapeName.MouthDimpleRight,
                nameof(BlendShapeName.MouthFrownLeft)      => (int)BlendShapeName.MouthFrownLeft,
                nameof(BlendShapeName.MouthFrownRight)     => (int)BlendShapeName.MouthFrownRight,
                nameof(BlendShapeName.MouthFunnel)         => (int)BlendShapeName.MouthFunnel,
                nameof(BlendShapeName.MouthLeft)           => (int)BlendShapeName.MouthLeft,
                nameof(BlendShapeName.MouthLowerDownLeft)  => (int)BlendShapeName.MouthLowerDownLeft,
                nameof(BlendShapeName.MouthLowerDownRight) => (int)BlendShapeName.MouthLowerDownRight,
                nameof(BlendShapeName.MouthPressLeft)      => (int)BlendShapeName.MouthPressLeft,
                nameof(BlendShapeName.MouthPressRight)     => (int)BlendShapeName.MouthPressRight,
                nameof(BlendShapeName.MouthPucker)         => (int)BlendShapeName.MouthPucker,
                nameof(BlendShapeName.MouthRight)          => (int)BlendShapeName.MouthRight,
                nameof(BlendShapeName.MouthRollLower)      => (int)BlendShapeName.MouthRollLower,
                nameof(BlendShapeName.MouthRollUpper)      => (int)BlendShapeName.MouthRollUpper,
                nameof(BlendShapeName.MouthShrugLower)     => (int)BlendShapeName.MouthShrugLower,
                nameof(BlendShapeName.MouthShrugUpper)     => (int)BlendShapeName.MouthShrugUpper,
                nameof(BlendShapeName.MouthSmileLeft)      => (int)BlendShapeName.MouthSmileLeft,
                nameof(BlendShapeName.MouthSmileRight)     => (int)BlendShapeName.MouthSmileRight,
                nameof(BlendShapeName.MouthStretchLeft)    => (int)BlendShapeName.MouthStretchLeft,
                nameof(BlendShapeName.MouthStretchRight)   => (int)BlendShapeName.MouthStretchRight,
                nameof(BlendShapeName.MouthUpperUpLeft)    => (int)BlendShapeName.MouthUpperUpLeft,
                nameof(BlendShapeName.MouthUpperUpRight)   => (int)BlendShapeName.MouthUpperUpRight,
                nameof(BlendShapeName.NoseSneerLeft)       => (int)BlendShapeName.NoseSneerLeft,
                nameof(BlendShapeName.NoseSneerRight)      => (int)BlendShapeName.NoseSneerRight,
                nameof(BlendShapeName.TongueOut)           => (int)BlendShapeName.TongueOut,

                // Camel case
                nameof(BlendShapeNameInCamelCase.browDownLeft)        => (int)BlendShapeNameInCamelCase.browDownLeft,
                nameof(BlendShapeNameInCamelCase.browDownRight)       => (int)BlendShapeNameInCamelCase.browDownRight,
                nameof(BlendShapeNameInCamelCase.browInnerUp)         => (int)BlendShapeNameInCamelCase.browInnerUp,
                nameof(BlendShapeNameInCamelCase.browOuterUpLeft)     => (int)BlendShapeNameInCamelCase.browOuterUpLeft,
                nameof(BlendShapeNameInCamelCase.browOuterUpRight)    => (int)BlendShapeNameInCamelCase.browOuterUpRight,
                nameof(BlendShapeNameInCamelCase.cheekPuff)           => (int)BlendShapeNameInCamelCase.cheekPuff,
                nameof(BlendShapeNameInCamelCase.cheekSquintLeft)     => (int)BlendShapeNameInCamelCase.cheekSquintLeft,
                nameof(BlendShapeNameInCamelCase.cheekSquintRight)    => (int)BlendShapeNameInCamelCase.cheekSquintRight,
                nameof(BlendShapeNameInCamelCase.eyeBlinkLeft)        => (int)BlendShapeNameInCamelCase.eyeBlinkLeft,
                nameof(BlendShapeNameInCamelCase.eyeBlinkRight)       => (int)BlendShapeNameInCamelCase.eyeBlinkRight,
                nameof(BlendShapeNameInCamelCase.eyeLookDownLeft)     => (int)BlendShapeNameInCamelCase.eyeLookDownLeft,
                nameof(BlendShapeNameInCamelCase.eyeLookDownRight)    => (int)BlendShapeNameInCamelCase.eyeLookDownRight,
                nameof(BlendShapeNameInCamelCase.eyeLookInLeft)       => (int)BlendShapeNameInCamelCase.eyeLookInLeft,
                nameof(BlendShapeNameInCamelCase.eyeLookInRight)      => (int)BlendShapeNameInCamelCase.eyeLookInRight,
                nameof(BlendShapeNameInCamelCase.eyeLookOutLeft)      => (int)BlendShapeNameInCamelCase.eyeLookOutLeft,
                nameof(BlendShapeNameInCamelCase.eyeLookOutRight)     => (int)BlendShapeNameInCamelCase.eyeLookOutRight,
                nameof(BlendShapeNameInCamelCase.eyeLookUpLeft)       => (int)BlendShapeNameInCamelCase.eyeLookUpLeft,
                nameof(BlendShapeNameInCamelCase.eyeLookUpRight)      => (int)BlendShapeNameInCamelCase.eyeLookUpRight,
                nameof(BlendShapeNameInCamelCase.eyeSquintLeft)       => (int)BlendShapeNameInCamelCase.eyeSquintLeft,
                nameof(BlendShapeNameInCamelCase.eyeSquintRight)      => (int)BlendShapeNameInCamelCase.eyeSquintRight,
                nameof(BlendShapeNameInCamelCase.eyeWideLeft)         => (int)BlendShapeNameInCamelCase.eyeWideLeft,
                nameof(BlendShapeNameInCamelCase.eyeWideRight)        => (int)BlendShapeNameInCamelCase.eyeWideRight,
                nameof(BlendShapeNameInCamelCase.jawForward)          => (int)BlendShapeNameInCamelCase.jawForward,
                nameof(BlendShapeNameInCamelCase.jawLeft)             => (int)BlendShapeNameInCamelCase.jawLeft,
                nameof(BlendShapeNameInCamelCase.jawOpen)             => (int)BlendShapeNameInCamelCase.jawOpen,
                nameof(BlendShapeNameInCamelCase.jawRight)            => (int)BlendShapeNameInCamelCase.jawRight,
                nameof(BlendShapeNameInCamelCase.mouthClose)          => (int)BlendShapeNameInCamelCase.mouthClose,
                nameof(BlendShapeNameInCamelCase.mouthDimpleLeft)     => (int)BlendShapeNameInCamelCase.mouthDimpleLeft,
                nameof(BlendShapeNameInCamelCase.mouthDimpleRight)    => (int)BlendShapeNameInCamelCase.mouthDimpleRight,
                nameof(BlendShapeNameInCamelCase.mouthFrownLeft)      => (int)BlendShapeNameInCamelCase.mouthFrownLeft,
                nameof(BlendShapeNameInCamelCase.mouthFrownRight)     => (int)BlendShapeNameInCamelCase.mouthFrownRight,
                nameof(BlendShapeNameInCamelCase.mouthFunnel)         => (int)BlendShapeNameInCamelCase.mouthFunnel,
                nameof(BlendShapeNameInCamelCase.mouthLeft)           => (int)BlendShapeNameInCamelCase.mouthLeft,
                nameof(BlendShapeNameInCamelCase.mouthLowerDownLeft)  => (int)BlendShapeNameInCamelCase.mouthLowerDownLeft,
                nameof(BlendShapeNameInCamelCase.mouthLowerDownRight) => (int)BlendShapeNameInCamelCase.mouthLowerDownRight,
                nameof(BlendShapeNameInCamelCase.mouthPressLeft)      => (int)BlendShapeNameInCamelCase.mouthPressLeft,
                nameof(BlendShapeNameInCamelCase.mouthPressRight)     => (int)BlendShapeNameInCamelCase.mouthPressRight,
                nameof(BlendShapeNameInCamelCase.mouthPucker)         => (int)BlendShapeNameInCamelCase.mouthPucker,
                nameof(BlendShapeNameInCamelCase.mouthRight)          => (int)BlendShapeNameInCamelCase.mouthRight,
                nameof(BlendShapeNameInCamelCase.mouthRollLower)      => (int)BlendShapeNameInCamelCase.mouthRollLower,
                nameof(BlendShapeNameInCamelCase.mouthRollUpper)      => (int)BlendShapeNameInCamelCase.mouthRollUpper,
                nameof(BlendShapeNameInCamelCase.mouthShrugLower)     => (int)BlendShapeNameInCamelCase.mouthShrugLower,
                nameof(BlendShapeNameInCamelCase.mouthShrugUpper)     => (int)BlendShapeNameInCamelCase.mouthShrugUpper,
                nameof(BlendShapeNameInCamelCase.mouthSmileLeft)      => (int)BlendShapeNameInCamelCase.mouthSmileLeft,
                nameof(BlendShapeNameInCamelCase.mouthSmileRight)     => (int)BlendShapeNameInCamelCase.mouthSmileRight,
                nameof(BlendShapeNameInCamelCase.mouthStretchLeft)    => (int)BlendShapeNameInCamelCase.mouthStretchLeft,
                nameof(BlendShapeNameInCamelCase.mouthStretchRight)   => (int)BlendShapeNameInCamelCase.mouthStretchRight,
                nameof(BlendShapeNameInCamelCase.mouthUpperUpLeft)    => (int)BlendShapeNameInCamelCase.mouthUpperUpLeft,
                nameof(BlendShapeNameInCamelCase.mouthUpperUpRight)   => (int)BlendShapeNameInCamelCase.mouthUpperUpRight,
                nameof(BlendShapeNameInCamelCase.noseSneerLeft)       => (int)BlendShapeNameInCamelCase.noseSneerLeft,
                nameof(BlendShapeNameInCamelCase.noseSneerRight)      => (int)BlendShapeNameInCamelCase.noseSneerRight,
                nameof(BlendShapeNameInCamelCase.tongueOut)           => (int)BlendShapeNameInCamelCase.tongueOut,

                _ => -1,
            };
            return index;
        }

        public static int GetBlendShapeIndex(BlendShapeName blendShapeName)
        {
            var index = blendShapeName switch
            {
                BlendShapeName.BrowDownLeft        => (int)InternalBlendShapeName.browDown_L,
                BlendShapeName.BrowDownRight       => (int)InternalBlendShapeName.browDown_R,
                BlendShapeName.BrowInnerUp         => (int)InternalBlendShapeName.browInnerUp,
                BlendShapeName.BrowOuterUpLeft     => (int)InternalBlendShapeName.browOuterUp_L,
                BlendShapeName.BrowOuterUpRight    => (int)InternalBlendShapeName.browOuterUp_R,
                BlendShapeName.CheekPuff           => (int)InternalBlendShapeName.cheekPuff,
                BlendShapeName.CheekSquintLeft     => (int)InternalBlendShapeName.cheekSquint_L,
                BlendShapeName.CheekSquintRight    => (int)InternalBlendShapeName.cheekSquint_R,
                BlendShapeName.EyeBlinkLeft        => (int)InternalBlendShapeName.eyeBlink_L,
                BlendShapeName.EyeBlinkRight       => (int)InternalBlendShapeName.eyeBlink_R,
                BlendShapeName.EyeLookDownLeft     => (int)InternalBlendShapeName.eyeLookDown_L,
                BlendShapeName.EyeLookDownRight    => (int)InternalBlendShapeName.eyeLookDown_R,
                BlendShapeName.EyeLookInLeft       => (int)InternalBlendShapeName.eyeLookIn_L,
                BlendShapeName.EyeLookInRight      => (int)InternalBlendShapeName.eyeLookIn_R,
                BlendShapeName.EyeLookOutLeft      => (int)InternalBlendShapeName.eyeLookOut_L,
                BlendShapeName.EyeLookOutRight     => (int)InternalBlendShapeName.eyeLookOut_R,
                BlendShapeName.EyeLookUpLeft       => (int)InternalBlendShapeName.eyeLookUp_L,
                BlendShapeName.EyeLookUpRight      => (int)InternalBlendShapeName.eyeLookUp_R,
                BlendShapeName.EyeSquintLeft       => (int)InternalBlendShapeName.eyeSquint_L,
                BlendShapeName.EyeSquintRight      => (int)InternalBlendShapeName.eyeSquint_R,
                BlendShapeName.EyeWideLeft         => (int)InternalBlendShapeName.eyeWide_L,
                BlendShapeName.EyeWideRight        => (int)InternalBlendShapeName.eyeWide_R,
                BlendShapeName.JawForward          => (int)InternalBlendShapeName.jawForward,
                BlendShapeName.JawLeft             => (int)InternalBlendShapeName.jawLeft,
                BlendShapeName.JawOpen             => (int)InternalBlendShapeName.jawOpen,
                BlendShapeName.JawRight            => (int)InternalBlendShapeName.jawRight,
                BlendShapeName.MouthClose          => (int)InternalBlendShapeName.mouthClose,
                BlendShapeName.MouthDimpleLeft     => (int)InternalBlendShapeName.mouthDimple_L,
                BlendShapeName.MouthDimpleRight    => (int)InternalBlendShapeName.mouthDimple_R,
                BlendShapeName.MouthFrownLeft      => (int)InternalBlendShapeName.mouthFrown_L,
                BlendShapeName.MouthFrownRight     => (int)InternalBlendShapeName.mouthFrown_R,
                BlendShapeName.MouthFunnel         => (int)InternalBlendShapeName.mouthFunnel,
                BlendShapeName.MouthLeft           => (int)InternalBlendShapeName.mouthLeft,
                BlendShapeName.MouthLowerDownLeft  => (int)InternalBlendShapeName.mouthLowerDown_L,
                BlendShapeName.MouthLowerDownRight => (int)InternalBlendShapeName.mouthLowerDown_R,
                BlendShapeName.MouthPressLeft      => (int)InternalBlendShapeName.mouthPress_L,
                BlendShapeName.MouthPressRight     => (int)InternalBlendShapeName.mouthPress_R,
                BlendShapeName.MouthPucker         => (int)InternalBlendShapeName.mouthPucker,
                BlendShapeName.MouthRight          => (int)InternalBlendShapeName.mouthRight,
                BlendShapeName.MouthRollLower      => (int)InternalBlendShapeName.mouthRollLower,
                BlendShapeName.MouthRollUpper      => (int)InternalBlendShapeName.mouthRollUpper,
                BlendShapeName.MouthShrugLower     => (int)InternalBlendShapeName.mouthShrugLower,
                BlendShapeName.MouthShrugUpper     => (int)InternalBlendShapeName.mouthShrugUpper,
                BlendShapeName.MouthSmileLeft      => (int)InternalBlendShapeName.mouthSmile_L,
                BlendShapeName.MouthSmileRight     => (int)InternalBlendShapeName.mouthSmile_R,
                BlendShapeName.MouthStretchLeft    => (int)InternalBlendShapeName.mouthStretch_L,
                BlendShapeName.MouthStretchRight   => (int)InternalBlendShapeName.mouthStretch_R,
                BlendShapeName.MouthUpperUpLeft    => (int)InternalBlendShapeName.mouthUpperUp_L,
                BlendShapeName.MouthUpperUpRight   => (int)InternalBlendShapeName.mouthUpperUp_R,
                BlendShapeName.NoseSneerLeft       => (int)InternalBlendShapeName.noseSneer_L,
                BlendShapeName.NoseSneerRight      => (int)InternalBlendShapeName.noseSneer_R,
                BlendShapeName.TongueOut           => (int)InternalBlendShapeName.tongueOut,
                _ => -1,
            };
            return index;
        }

        public static string GetBlendShapeName(int blendShapeIndex)
        {
            var name = blendShapeIndex switch
            {
                (int)BlendShapeName.BrowDownLeft        => nameof(BlendShapeName.BrowDownLeft),
                (int)BlendShapeName.BrowDownRight       => nameof(BlendShapeName.BrowDownRight),
                (int)BlendShapeName.BrowInnerUp         => nameof(BlendShapeName.BrowInnerUp),
                (int)BlendShapeName.BrowOuterUpLeft     => nameof(BlendShapeName.BrowOuterUpLeft),
                (int)BlendShapeName.BrowOuterUpRight    => nameof(BlendShapeName.BrowOuterUpRight),
                (int)BlendShapeName.CheekPuff           => nameof(BlendShapeName.CheekPuff),
                (int)BlendShapeName.CheekSquintLeft     => nameof(BlendShapeName.CheekSquintLeft),
                (int)BlendShapeName.CheekSquintRight    => nameof(BlendShapeName.CheekSquintRight),
                (int)BlendShapeName.EyeBlinkLeft        => nameof(BlendShapeName.EyeBlinkLeft),
                (int)BlendShapeName.EyeBlinkRight       => nameof(BlendShapeName.EyeBlinkRight),
                (int)BlendShapeName.EyeLookDownLeft     => nameof(BlendShapeName.EyeLookDownLeft),
                (int)BlendShapeName.EyeLookDownRight    => nameof(BlendShapeName.EyeLookDownRight),
                (int)BlendShapeName.EyeLookInLeft       => nameof(BlendShapeName.EyeLookInLeft),
                (int)BlendShapeName.EyeLookInRight      => nameof(BlendShapeName.EyeLookInRight),
                (int)BlendShapeName.EyeLookOutLeft      => nameof(BlendShapeName.EyeLookOutLeft),
                (int)BlendShapeName.EyeLookOutRight     => nameof(BlendShapeName.EyeLookOutRight),
                (int)BlendShapeName.EyeLookUpLeft       => nameof(BlendShapeName.EyeLookUpLeft),
                (int)BlendShapeName.EyeLookUpRight      => nameof(BlendShapeName.EyeLookUpRight),
                (int)BlendShapeName.EyeSquintLeft       => nameof(BlendShapeName.EyeSquintLeft),
                (int)BlendShapeName.EyeSquintRight      => nameof(BlendShapeName.EyeSquintRight),
                (int)BlendShapeName.EyeWideLeft         => nameof(BlendShapeName.EyeWideLeft),
                (int)BlendShapeName.EyeWideRight        => nameof(BlendShapeName.EyeWideRight),
                (int)BlendShapeName.JawForward          => nameof(BlendShapeName.JawForward),
                (int)BlendShapeName.JawLeft             => nameof(BlendShapeName.JawLeft),
                (int)BlendShapeName.JawOpen             => nameof(BlendShapeName.JawOpen),
                (int)BlendShapeName.JawRight            => nameof(BlendShapeName.JawRight),
                (int)BlendShapeName.MouthClose          => nameof(BlendShapeName.MouthClose),
                (int)BlendShapeName.MouthDimpleLeft     => nameof(BlendShapeName.MouthDimpleLeft),
                (int)BlendShapeName.MouthDimpleRight    => nameof(BlendShapeName.MouthDimpleRight),
                (int)BlendShapeName.MouthFrownLeft      => nameof(BlendShapeName.MouthFrownLeft),
                (int)BlendShapeName.MouthFrownRight     => nameof(BlendShapeName.MouthFrownRight),
                (int)BlendShapeName.MouthFunnel         => nameof(BlendShapeName.MouthFunnel),
                (int)BlendShapeName.MouthLeft           => nameof(BlendShapeName.MouthLeft),
                (int)BlendShapeName.MouthLowerDownLeft  => nameof(BlendShapeName.MouthLowerDownLeft),
                (int)BlendShapeName.MouthLowerDownRight => nameof(BlendShapeName.MouthLowerDownRight),
                (int)BlendShapeName.MouthPressLeft      => nameof(BlendShapeName.MouthPressLeft),
                (int)BlendShapeName.MouthPressRight     => nameof(BlendShapeName.MouthPressRight),
                (int)BlendShapeName.MouthPucker         => nameof(BlendShapeName.MouthPucker),
                (int)BlendShapeName.MouthRight          => nameof(BlendShapeName.MouthRight),
                (int)BlendShapeName.MouthRollLower      => nameof(BlendShapeName.MouthRollLower),
                (int)BlendShapeName.MouthRollUpper      => nameof(BlendShapeName.MouthRollUpper),
                (int)BlendShapeName.MouthShrugLower     => nameof(BlendShapeName.MouthShrugLower),
                (int)BlendShapeName.MouthShrugUpper     => nameof(BlendShapeName.MouthShrugUpper),
                (int)BlendShapeName.MouthSmileLeft      => nameof(BlendShapeName.MouthSmileLeft),
                (int)BlendShapeName.MouthSmileRight     => nameof(BlendShapeName.MouthSmileRight),
                (int)BlendShapeName.MouthStretchLeft    => nameof(BlendShapeName.MouthStretchLeft),
                (int)BlendShapeName.MouthStretchRight   => nameof(BlendShapeName.MouthStretchRight),
                (int)BlendShapeName.MouthUpperUpLeft    => nameof(BlendShapeName.MouthUpperUpLeft),
                (int)BlendShapeName.MouthUpperUpRight   => nameof(BlendShapeName.MouthUpperUpRight),
                (int)BlendShapeName.NoseSneerLeft       => nameof(BlendShapeName.NoseSneerLeft),
                (int)BlendShapeName.NoseSneerRight      => nameof(BlendShapeName.NoseSneerRight),
                (int)BlendShapeName.TongueOut           => nameof(BlendShapeName.TongueOut),
                _ => "Unknown",
            };
            return name;
        }

        public static string GetBlendShapeNameInCamelCase(int blendShapeIndex)
        {
            var name = blendShapeIndex switch
            {
                (int)BlendShapeNameInCamelCase.browDownLeft        => nameof(BlendShapeNameInCamelCase.browDownLeft),
                (int)BlendShapeNameInCamelCase.browDownRight       => nameof(BlendShapeNameInCamelCase.browDownRight),
                (int)BlendShapeNameInCamelCase.browInnerUp         => nameof(BlendShapeNameInCamelCase.browInnerUp),
                (int)BlendShapeNameInCamelCase.browOuterUpLeft     => nameof(BlendShapeNameInCamelCase.browOuterUpLeft),
                (int)BlendShapeNameInCamelCase.browOuterUpRight    => nameof(BlendShapeNameInCamelCase.browOuterUpRight),
                (int)BlendShapeNameInCamelCase.cheekPuff           => nameof(BlendShapeNameInCamelCase.cheekPuff),
                (int)BlendShapeNameInCamelCase.cheekSquintLeft     => nameof(BlendShapeNameInCamelCase.cheekSquintLeft),
                (int)BlendShapeNameInCamelCase.cheekSquintRight    => nameof(BlendShapeNameInCamelCase.cheekSquintRight),
                (int)BlendShapeNameInCamelCase.eyeBlinkLeft        => nameof(BlendShapeNameInCamelCase.eyeBlinkLeft),
                (int)BlendShapeNameInCamelCase.eyeBlinkRight       => nameof(BlendShapeNameInCamelCase.eyeBlinkRight),
                (int)BlendShapeNameInCamelCase.eyeLookDownLeft     => nameof(BlendShapeNameInCamelCase.eyeLookDownLeft),
                (int)BlendShapeNameInCamelCase.eyeLookDownRight    => nameof(BlendShapeNameInCamelCase.eyeLookDownRight),
                (int)BlendShapeNameInCamelCase.eyeLookInLeft       => nameof(BlendShapeNameInCamelCase.eyeLookInLeft),
                (int)BlendShapeNameInCamelCase.eyeLookInRight      => nameof(BlendShapeNameInCamelCase.eyeLookInRight),
                (int)BlendShapeNameInCamelCase.eyeLookOutLeft      => nameof(BlendShapeNameInCamelCase.eyeLookOutLeft),
                (int)BlendShapeNameInCamelCase.eyeLookOutRight     => nameof(BlendShapeNameInCamelCase.eyeLookOutRight),
                (int)BlendShapeNameInCamelCase.eyeLookUpLeft       => nameof(BlendShapeNameInCamelCase.eyeLookUpLeft),
                (int)BlendShapeNameInCamelCase.eyeLookUpRight      => nameof(BlendShapeNameInCamelCase.eyeLookUpRight),
                (int)BlendShapeNameInCamelCase.eyeSquintLeft       => nameof(BlendShapeNameInCamelCase.eyeSquintLeft),
                (int)BlendShapeNameInCamelCase.eyeSquintRight      => nameof(BlendShapeNameInCamelCase.eyeSquintRight),
                (int)BlendShapeNameInCamelCase.eyeWideLeft         => nameof(BlendShapeNameInCamelCase.eyeWideLeft),
                (int)BlendShapeNameInCamelCase.eyeWideRight        => nameof(BlendShapeNameInCamelCase.eyeWideRight),
                (int)BlendShapeNameInCamelCase.jawForward          => nameof(BlendShapeNameInCamelCase.jawForward),
                (int)BlendShapeNameInCamelCase.jawLeft             => nameof(BlendShapeNameInCamelCase.jawLeft),
                (int)BlendShapeNameInCamelCase.jawOpen             => nameof(BlendShapeNameInCamelCase.jawOpen),
                (int)BlendShapeNameInCamelCase.jawRight            => nameof(BlendShapeNameInCamelCase.jawRight),
                (int)BlendShapeNameInCamelCase.mouthClose          => nameof(BlendShapeNameInCamelCase.mouthClose),
                (int)BlendShapeNameInCamelCase.mouthDimpleLeft     => nameof(BlendShapeNameInCamelCase.mouthDimpleLeft),
                (int)BlendShapeNameInCamelCase.mouthDimpleRight    => nameof(BlendShapeNameInCamelCase.mouthDimpleRight),
                (int)BlendShapeNameInCamelCase.mouthFrownLeft      => nameof(BlendShapeNameInCamelCase.mouthFrownLeft),
                (int)BlendShapeNameInCamelCase.mouthFrownRight     => nameof(BlendShapeNameInCamelCase.mouthFrownRight),
                (int)BlendShapeNameInCamelCase.mouthFunnel         => nameof(BlendShapeNameInCamelCase.mouthFunnel),
                (int)BlendShapeNameInCamelCase.mouthLeft           => nameof(BlendShapeNameInCamelCase.mouthLeft),
                (int)BlendShapeNameInCamelCase.mouthLowerDownLeft  => nameof(BlendShapeNameInCamelCase.mouthLowerDownLeft),
                (int)BlendShapeNameInCamelCase.mouthLowerDownRight => nameof(BlendShapeNameInCamelCase.mouthLowerDownRight),
                (int)BlendShapeNameInCamelCase.mouthPressLeft      => nameof(BlendShapeNameInCamelCase.mouthPressLeft),
                (int)BlendShapeNameInCamelCase.mouthPressRight     => nameof(BlendShapeNameInCamelCase.mouthPressRight),
                (int)BlendShapeNameInCamelCase.mouthPucker         => nameof(BlendShapeNameInCamelCase.mouthPucker),
                (int)BlendShapeNameInCamelCase.mouthRight          => nameof(BlendShapeNameInCamelCase.mouthRight),
                (int)BlendShapeNameInCamelCase.mouthRollLower      => nameof(BlendShapeNameInCamelCase.mouthRollLower),
                (int)BlendShapeNameInCamelCase.mouthRollUpper      => nameof(BlendShapeNameInCamelCase.mouthRollUpper),
                (int)BlendShapeNameInCamelCase.mouthShrugLower     => nameof(BlendShapeNameInCamelCase.mouthShrugLower),
                (int)BlendShapeNameInCamelCase.mouthShrugUpper     => nameof(BlendShapeNameInCamelCase.mouthShrugUpper),
                (int)BlendShapeNameInCamelCase.mouthSmileLeft      => nameof(BlendShapeNameInCamelCase.mouthSmileLeft),
                (int)BlendShapeNameInCamelCase.mouthSmileRight     => nameof(BlendShapeNameInCamelCase.mouthSmileRight),
                (int)BlendShapeNameInCamelCase.mouthStretchLeft    => nameof(BlendShapeNameInCamelCase.mouthStretchLeft),
                (int)BlendShapeNameInCamelCase.mouthStretchRight   => nameof(BlendShapeNameInCamelCase.mouthStretchRight),
                (int)BlendShapeNameInCamelCase.mouthUpperUpLeft    => nameof(BlendShapeNameInCamelCase.mouthUpperUpLeft),
                (int)BlendShapeNameInCamelCase.mouthUpperUpRight   => nameof(BlendShapeNameInCamelCase.mouthUpperUpRight),
                (int)BlendShapeNameInCamelCase.noseSneerLeft       => nameof(BlendShapeNameInCamelCase.noseSneerLeft),
                (int)BlendShapeNameInCamelCase.noseSneerRight      => nameof(BlendShapeNameInCamelCase.noseSneerRight),
                (int)BlendShapeNameInCamelCase.tongueOut           => nameof(BlendShapeNameInCamelCase.tongueOut),
                _ => "unknown",
            };
            return name;
        }
    }
}